{
  "uid" : "6bd1b128304759fb",
  "name" : "打开微信，进入小程序首页，断言成功",
  "fullName" : "testcase.djc_demo.test_005.TestAppLets#test_into_home_000",
  "historyId" : "f636f903c5dae63a550b64097398b26c",
  "time" : {
    "start" : 1624365429024,
    "stop" : 1624365431040,
    "duration" : 2016
  },
  "description" : "打开微信，登录小程序，进入小熊麦麦首页",
  "descriptionHtml" : "<p>打开微信，登录小程序，进入小熊麦麦首页</p>\n",
  "status" : "broken",
  "statusMessage" : "RuntimeError: USB device 10.15.20.72:20065 is offline",
  "statusTrace" : "self = <project_test.ebuy_app.testcase.djc_demo.test_005.TestAppLets object at 0x000002576B5515C0>, device_name = '10.15.20.72:20065'\n\n    @allure.feature('UI测试demo')\n    @allure.title(\"打开微信，进入小程序首页，断言成功\")\n    @allure.severity('blocker')\n    @allure.description(\"打开微信，登录小程序，进入小熊麦麦首页\")\n    def test_into_home_000(self, device_name):\n>       d = u2.connect(device_name)\n\ntestcase\\djc_demo\\test_005.py:23: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \nD:\\myenv\\ui_env\\lib\\site-packages\\uiautomator2\\__init__.py:1830: in connect\n    return connect_usb(addr)\nD:\\myenv\\ui_env\\lib\\site-packages\\uiautomator2\\__init__.py:1871: in connect_usb\n    return Device(serial)\nD:\\myenv\\ui_env\\lib\\site-packages\\uiautomator2\\__init__.py:242: in __init__\n    wlan_ip = self.wlan_ip\nD:\\myenv\\ui_env\\lib\\site-packages\\uiautomator2\\__init__.py:408: in wlan_ip\n    ip = self.http.get(\"/wlan/ip\").text.strip()\nD:\\myenv\\ui_env\\lib\\site-packages\\requests\\sessions.py:521: in get\n    return self.request('GET', url, **kwargs)\nD:\\myenv\\ui_env\\lib\\site-packages\\uiautomator2\\__init__.py:208: in request\n    self.__client._prepare_atx_agent()\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <uiautomator2.Device object at 0x000002576B551828>\n\n    def _prepare_atx_agent(self):\n        \"\"\"\n        check running -> push binary -> launch\n        \"\"\"\n        assert self._serial, \"Device serialno is required\"\n        _d = self._wait_for_device()\n        if not _d:\n>           raise RuntimeError(\"USB device %s is offline\" % self._serial)\nE           RuntimeError: USB device 10.15.20.72:20065 is offline\n\nD:\\myenv\\ui_env\\lib\\site-packages\\uiautomator2\\__init__.py:286: RuntimeError",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ {
    "name" : "device_name",
    "time" : {
      "start" : 1624365429023,
      "stop" : 1624365429023,
      "duration" : 0
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "shouldDisplayMessage" : false,
    "attachmentsCount" : 0,
    "stepsCount" : 0,
    "hasContent" : false
  } ],
  "testStage" : {
    "description" : "打开微信，登录小程序，进入小熊麦麦首页",
    "status" : "broken",
    "statusMessage" : "RuntimeError: USB device 10.15.20.72:20065 is offline",
    "statusTrace" : "self = <project_test.ebuy_app.testcase.djc_demo.test_005.TestAppLets object at 0x000002576B5515C0>, device_name = '10.15.20.72:20065'\n\n    @allure.feature('UI测试demo')\n    @allure.title(\"打开微信，进入小程序首页，断言成功\")\n    @allure.severity('blocker')\n    @allure.description(\"打开微信，登录小程序，进入小熊麦麦首页\")\n    def test_into_home_000(self, device_name):\n>       d = u2.connect(device_name)\n\ntestcase\\djc_demo\\test_005.py:23: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \nD:\\myenv\\ui_env\\lib\\site-packages\\uiautomator2\\__init__.py:1830: in connect\n    return connect_usb(addr)\nD:\\myenv\\ui_env\\lib\\site-packages\\uiautomator2\\__init__.py:1871: in connect_usb\n    return Device(serial)\nD:\\myenv\\ui_env\\lib\\site-packages\\uiautomator2\\__init__.py:242: in __init__\n    wlan_ip = self.wlan_ip\nD:\\myenv\\ui_env\\lib\\site-packages\\uiautomator2\\__init__.py:408: in wlan_ip\n    ip = self.http.get(\"/wlan/ip\").text.strip()\nD:\\myenv\\ui_env\\lib\\site-packages\\requests\\sessions.py:521: in get\n    return self.request('GET', url, **kwargs)\nD:\\myenv\\ui_env\\lib\\site-packages\\uiautomator2\\__init__.py:208: in request\n    self.__client._prepare_atx_agent()\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <uiautomator2.Device object at 0x000002576B551828>\n\n    def _prepare_atx_agent(self):\n        \"\"\"\n        check running -> push binary -> launch\n        \"\"\"\n        assert self._serial, \"Device serialno is required\"\n        _d = self._wait_for_device()\n        if not _d:\n>           raise RuntimeError(\"USB device %s is offline\" % self._serial)\nE           RuntimeError: USB device 10.15.20.72:20065 is offline\n\nD:\\myenv\\ui_env\\lib\\site-packages\\uiautomator2\\__init__.py:286: RuntimeError",
    "steps" : [ ],
    "attachments" : [ {
      "uid" : "7840d5c04df2809d",
      "name" : "log",
      "source" : "7840d5c04df2809d.txt",
      "type" : "text/plain",
      "size" : 217
    }, {
      "uid" : "4bb0644f123b9f03",
      "name" : "stderr",
      "source" : "4bb0644f123b9f03.txt",
      "type" : "text/plain",
      "size" : 160
    } ],
    "parameters" : [ ],
    "shouldDisplayMessage" : true,
    "attachmentsCount" : 2,
    "stepsCount" : 0,
    "hasContent" : true
  },
  "afterStages" : [ ],
  "labels" : [ {
    "name" : "feature",
    "value" : "UI测试demo"
  }, {
    "name" : "severity",
    "value" : "blocker"
  }, {
    "name" : "parentSuite",
    "value" : "testcase.djc_demo"
  }, {
    "name" : "suite",
    "value" : "test_005"
  }, {
    "name" : "subSuite",
    "value" : "TestAppLets"
  }, {
    "name" : "host",
    "value" : "DT-DONGJUNCHAO"
  }, {
    "name" : "thread",
    "value" : "3908-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "testcase.djc_demo.test_005"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "blocker",
    "retries" : [ {
      "uid" : "ac66afe4d5cd37d9",
      "status" : "broken",
      "statusDetails" : "RuntimeError: USB device 10.15.20.72:20065 is offline",
      "time" : {
        "start" : 1624365425682,
        "stop" : 1624365427705,
        "duration" : 2023
      }
    } ],
    "categories" : [ {
      "name" : "Test defects",
      "matchedStatuses" : [ ],
      "flaky" : false
    } ],
    "tags" : [ ]
  },
  "source" : "6bd1b128304759fb.json",
  "parameterValues" : [ ]
}